import bcrypt from 'bcryptjs'
import { Product } from './models/productModel'
import { User } from './models/userModel'

export const sampleProducts: Product[] = [
  {
    name: 'Iphone 14',
    slug: 'iphone-14',
    category: 'Phone',
    image: '../images/iphone-14.jpg',
    price: 700,
    countInStock: 10,
    brand: 'Apple',
    rating: 4.5,
    numReviews: 10,
    description: '3 months used',
  },
  {
    name: 'Iphone 14 Plus',
    slug: 'iphone-14-plus',
    category: 'Phone',
    image: '../images/iphone-14-Plus.jpg',
    price: 100,
    countInStock: 20,
    brand: 'Apple',
    rating: 4.0,
    numReviews: 10,
    description: '3 months used',
  },
  {
    name: 'Ipad 2022',
    slug: 'ipad-2022',
    category: 'Tab',
    image: '../images/ipad-22.jpg',
    price: 220,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'high quality product',
  },
  {
    name: 'Galaxy Watch 3',
    slug: 'galaxy-Watch-3',
    category: 'Pants',
    image: '../images/Galaxy-Watch.jpg',
    price: 78,
    countInStock: 15,
    brand: 'Samsung',
    rating: 4.5,
    numReviews: 14,
    description: 'high quality product',
  },
  {
    name: 'Realme K50i',
    slug: 'realme-k50i',
    category: 'Phone',
    image:
      'https://d3qqewlrl1nyfn.cloudfront.net/product/16849971621695332849.webp',
    price: 120,
    countInStock: 10,
    brand: 'Realme',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Iphone 11',
    slug: 'iphone-11',
    category: 'Phone',
    image:
      'https://d3qqewlrl1nyfn.cloudfront.net/product/16849136951738361931.webp',
    price: 120,
    countInStock: 10,
    brand: 'Apple',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Vivo T1 Pro',
    slug: 'vivo-t1-pro',
    category: 'Phone',
    image:
      'https://d3qqewlrl1nyfn.cloudfront.net/product/1685007783452594201.webp',
    price: 120,
    countInStock: 10,
    brand: 'Vivo',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Acer aspire N17C4',
    slug: 'acer-aspire-n17c4',
    category: 'Laptop',
    image:
      'https://d3qqewlrl1nyfn.cloudfront.net/product/1685023305471472481.webp',
    price: 120,
    countInStock: 10,
    brand: 'Acer',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
]
export const sampleUsers: User[] = [
  {
    name: 'Sajjad Hossain',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: true,
  },
  {
    name: 'John',
    email: 'user@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: false,
  },
]
